create_video = """Generate a concise and vivid description of a video scene, focusing on the essential visual elements. The description should be highly detailed yet succinct, similar to the example provided below. 

**Important: Output only the final description, without including the input information or any other text. Do not use backslashes or quotation marks in the output.**

**Example of Desired Output:**

The waves crash against the jagged rocks of the shoreline, sending spray high into the air. The rocks are a dark gray color, with sharp edges and deep crevices. The water is a clear blue-green, with white foam where the waves break against the rocks. The sky is a light gray, with a few white clouds dotting the horizon.

**Input Information (Do not include this in the output):**

- Setting: A beautiful beach
- Subject: Scenery
- Emotion: Tranquility, awe
- Style: Realistic, serene
- Composition: Wide, open
- Time: Sunset
- Color: Warm yellows, oranges, pinks, soft blues
- Elements: Ocean, sand, sky, setting sun, gentle waves, distant horizon
- Constraints: No people or man-made structures

**Guidelines for Description (Do not output these guidelines):**

1. **Brevity:** Be concise and to the point. Avoid overly flowery language or unnecessary adjectives.
2. **Precision:** Use specific and descriptive words that accurately convey the visual elements.
3. **Focus on Essentials:** Describe only the most important visual aspects of the scene. Omit minor details that don't significantly contribute to the overall picture.
4. **Show, Don't Tell:** Use descriptive language to paint a picture for the reader, rather than explicitly stating the emotions or atmosphere.
5. **Structure:** Follow a logical structure, describing elements in a way that makes sense visually (e.g., from foreground to background, or from the most prominent element to less prominent ones).

**Cinematic Shot Types, Camera Movements (Use these as guidelines to form your description, but do not output them):**

Cinematic Shot Types and Framing:
{
  - Extreme Long Shot (ELS): Used to show the subject from a distance, or the area in which the scene is taking place. Useful for establishing the setting.
  - Long Shot (LS): Shows the subject from top to bottom; for a person, this would be head to toes.
  - Full Shot (FS): Frames the subject from head to toe, with the subject roughly filling the frame.
  - Medium Shot (MS): Shows the subject from the waist up.
  - Medium Close-up (MCU): Frames the subject from the chest up.
  - Close-up (CU): Fills the screen with part of the subject, such as a person's head/face.
  - Extreme Close-up (ECU): Shows a detail of the subject, such as a person's eyes or mouth.
  - Over-the-Shoulder Shot: Shows the subject from behind the shoulder of another character.
  - Point-of-View Shot (POV): Shows a view from the subject's perspective.
  - Establishing Shot: Often the first shot of a scene, designed to show the audience where the action is taking place.
}

Camera Movements:
{
  - Pan: The camera horizontally swivels from a fixed position to follow action or reveal a scene.
  - Tilt: The camera moves up or down from a fixed position.
  - Zoom: The camera lens increases or decreases the magnification of the subject.
  - Dolly: The camera moves on a track or with a stabilizer toward or away from the subject.
  - Tracking: The camera follows alongside a moving subject.
  - Crane: The camera moves vertically on a crane or jib.
}"""