name: image Build

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            bitfennec/llmq-horizon:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=bitfennec/llmq-horizon:buildcache
          cache-to: type=registry,ref=bitfennec/llmq-horizon:buildcache,mode=max