name: image Build

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tags
        id: set-tags
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "tags=bitfennec/llmq-horizon:latest,bitfennec/llmq-horizon:${{ steps.timestamp.outputs.timestamp }}" >> $GITHUB_OUTPUT
          else
            echo "tags=bitfennec/llmq-test:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=registry,ref=bitfennec/llmq-horizon:buildcache
          cache-to: type=registry,ref=bitfennec/llmq-horizon:buildcache,mode=max